### ISSUE TITLE
No such method error call OneWeather API

### ISSUE THREAD

**Issue by sowens-csd** [tanzilzubair/open_weather_api_client#2] opened 2021-05-31 15:46 UTC
NoSuchMethodError (NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: []("1h"))

from line 141 in one_call_hourly_weather.dart. 

This is the call I was making:
```dart
OneCallWeatherFactory weatherFactory = OneCallWeatherFactory(
      apiKey: "my-key",
      settings: UnitSettings(
        windSpeedUnit: WindSpeedUnit.Kilometres_Hour,
      ),
      locationCoords: LocationCoords(
        longitude: lat,
        latitude: long,
      ),
    );

    RequestResponse<OneCallWeather?> result = await weatherFactory.getWeather();
```

Where 
lat = 43.653524
long = -79.383907

**Comment by tanzilzubair** [comment] 2021-05-31 15:48
Yep, I’ll look into it as soon as I can. You find anymore errors, please don’t hesitate to open more issues.

**Comment by tanzilzubair** [comment] 2021-06-01 17:00
@sowens-csd  I've been super busy so this might take a slightly longer amount of time than usual, but a glance at the code's telling me that this is also an issue with the rain parameters, where the server sends null for the fields pertaining to the amount of rain when rain has not occurred in a set duration.

I have not been able to dig deep yet, but what's confusing me is that I did build checks for this into the system that is to parse the rain (unlike the minutely ones, which I missed accidentally), so its hard for me to trace where exactly the code fails, as on paper, the checks are there.

What's also problematic is that I cannot reliably cause this error as the amount of rain will of course change in that particular area from when you called the code and when I'm calling it.

I estimate that with my current workload its going to take be about 2-3 days to scrounge together enough time for debugging and fixing this, but I'm confident that it will be done in this amount of time. I will of course be publishing an update to pub.dev as soon as I am done fixing it.

Sorry in advance that I cannot fix this earlier, and again, thank you for using my package.

**Comment by tanzilzubair** [comment] 2021-08-23 18:37
A new version of the package has been released, with several nullability big fixes, and try as I might I couldn't reproduce this issue exactly, so I'm closing this issue. If you still find this or any other issue in the new version of my package, please do not hesitate to open another issue.

Again, thank you for using my package.

**Closed as completed by tanzilzubair** 2021-08-23 18:37 UTC
Labels: bug
